version: 2.1
jobs:
  build:
    docker:
      - image: cimg/gcp:2022.11.1
    resource_class: small
    steps:
      - run: echo "Hello"
      - run: mkdir naaa
      - run: ls -la
      - run: pwd
      - persist_to_workspace:
          root: /home/circleci/
          paths: naaa
  downstream:        
    machine:
      image: ubuntu-2004:current
    resource_class: small
    steps:
      - attach_workspace:
          at: /home/circleci/
      - run: ls -la

workflows:
  btd:
    jobs:
      - build
      - downstream:
          requires:
            - build
